/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.algounix.Dashboards;

import com.algounix.Components.ScrollBar;
import com.algounix.GUI.SignOut;
import com.algounix.Panel.Pharmacy.PharmacyInvoice;
import com.algounix.Popup.Navigation;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.JFrame;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import raven.glasspanepopup.GlassPanePopup;

/**
 *
 * @author kusal
 */
public class DashboardLaboretory extends javax.swing.JFrame {

    Timer updateTimer;
    int DELAY = 100;

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardLaboretory() {
        initComponents();

        updateTimer = new Timer(DELAY, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Date currentTime = new Date();
                String TimeFormat = "HH:mm:ss";
                String DateFormat = "MMMM dd, yyyy";
                DateFormat formatTime = new SimpleDateFormat(TimeFormat);
                DateFormat formatDate = new SimpleDateFormat(DateFormat);
                String formattedTime = formatTime.format(currentTime);
                String formattedDate = formatDate.format(currentTime);
                jLabel3.setText(formattedTime);
                jLabel9.setText(formattedDate);

            }
        });

        updateTimer.start();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        FlatSVGIcon iconLogo = new FlatSVGIcon("com//algounix//Resources//HMS-Logo.svg", MenuLogo.getWidth(), MenuLogo.getHeight());
        MenuLogo.setIcon(iconLogo);
        this.setIconImage(new ImageIcon("com//algounix//MenuIcons//GRN.png").getImage());
        Image icon = new ImageIcon(this.getClass().getResource("/com/algounix/Resources/HMS-Logo.png")).getImage();
        this.setIconImage(icon);
        GlassPanePopup.install(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labDashboardLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        regLabel = new javax.swing.JLabel();
        patientListLabel = new javax.swing.JLabel();
        testListLabel = new javax.swing.JLabel();
        addReportLabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        doctorListLabel = new javax.swing.JLabel();
        patientReportLabel = new javax.swing.JLabel();
        MenuLogo = new javax.swing.JLabel();
        AdminDashboardSignOutbtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CardLayoutPanel = new javax.swing.JPanel();
        dashboardLaboretory1 = new com.algounix.Laboretory.DashboardLaboretory();
        addReportToTest1 = new com.algounix.Laboretory.AddReportToTest();
        registerTests1 = new com.algounix.Laboretory.RegisterTests();
        testList1 = new com.algounix.Laboretory.TestList();
        patientReportAndPrescription1 = new com.algounix.Panel.Doctor.PatientReportAndPrescription();
        patientList1 = new com.algounix.Panel.Doctor.PatientList();
        doctorList1 = new com.algounix.Panel.DoctorList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(137, 207, 243));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 688));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(137, 207, 243));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Dashboard.png"))); // NOI18N
        jLabel1.setText("Dashboard");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Patient.png"))); // NOI18N
        jLabel2.setText("Patients");

        labDashboardLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        labDashboardLabel.setText("Laboretory Dashboard");
        labDashboardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labDashboardLabelMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/GRN.png"))); // NOI18N
        jLabel25.setText("Lab Management");

        regLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        regLabel.setText("Registration for Lab Tests");
        regLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regLabelMouseClicked(evt);
            }
        });

        patientListLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        patientListLabel.setText("Registered Patinet List");
        patientListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientListLabelMouseClicked(evt);
            }
        });

        testListLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        testListLabel.setText("Test List");
        testListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testListLabelMouseClicked(evt);
            }
        });

        addReportLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        addReportLabel.setText("Add Reports to Lab Tests");
        addReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReportLabelMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Doctor.png"))); // NOI18N
        jLabel26.setText("Doctors");

        doctorListLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        doctorListLabel.setText("Doctor List");
        doctorListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorListLabelMouseClicked(evt);
            }
        });

        patientReportLabel.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        patientReportLabel.setText("Patinet Reports and Prescriptions");
        patientReportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientReportLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(labDashboardLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientListLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testListLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addReportLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doctorListLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientReportLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labDashboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doctorListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientReportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel3);

        AdminDashboardSignOutbtn.setFont(new java.awt.Font("Poppins", 3, 14)); // NOI18N
        AdminDashboardSignOutbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminDashboardSignOutbtn.setText("Sign Out");
        AdminDashboardSignOutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDashboardSignOutbtnMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins Light", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Unix Hospital");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(MenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDashboardSignOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDashboardSignOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(160, 233, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(803, 40));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 3, 18)); // NOI18N
        jLabel3.setText("12 : 30 AM");

        jLabel9.setFont(new java.awt.Font("Poppins Light", 3, 18)); // NOI18N
        jLabel9.setText("Date");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(823, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        CardLayoutPanel.setBackground(new java.awt.Color(205, 245, 253));
        CardLayoutPanel.setLayout(new java.awt.CardLayout());
        CardLayoutPanel.add(dashboardLaboretory1, "card3");
        CardLayoutPanel.add(addReportToTest1, "card3");
        CardLayoutPanel.add(registerTests1, "card4");
        CardLayoutPanel.add(testList1, "card5");
        CardLayoutPanel.add(patientReportAndPrescription1, "card6");
        CardLayoutPanel.add(patientList1, "card7");
        CardLayoutPanel.add(doctorList1, "card8");

        jPanel4.add(CardLayoutPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labDashboardLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labDashboardLabelMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(dashboardLaboretory1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_labDashboardLabelMouseClicked

    private void AdminDashboardSignOutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardSignOutbtnMouseClicked
        // TODO add your handling code here:
//        GlassPanePopup.showPopup(new Navigation());
        new SignOut().setVisible(true);
    }//GEN-LAST:event_AdminDashboardSignOutbtnMouseClicked

    private void patientListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientListLabelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_patientListLabelMouseClicked

    private void regLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regLabelMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(registerTests1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

    }//GEN-LAST:event_regLabelMouseClicked

    private void testListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testListLabelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(testList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_testListLabelMouseClicked

    private void addReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportLabelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(addReportToTest1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_addReportLabelMouseClicked

    private void doctorListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorListLabelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(doctorList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_doctorListLabelMouseClicked

    private void patientReportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientReportLabelMouseClicked
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientReportAndPrescription1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_patientReportLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardLaboretory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboardSignOutbtn;
    private javax.swing.JPanel CardLayoutPanel;
    private javax.swing.JLabel MenuLogo;
    private javax.swing.JLabel addReportLabel;
    private com.algounix.Laboretory.AddReportToTest addReportToTest1;
    private com.algounix.Laboretory.DashboardLaboretory dashboardLaboretory1;
    private com.algounix.Panel.DoctorList doctorList1;
    private javax.swing.JLabel doctorListLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labDashboardLabel;
    private com.algounix.Panel.Doctor.PatientList patientList1;
    private javax.swing.JLabel patientListLabel;
    private com.algounix.Panel.Doctor.PatientReportAndPrescription patientReportAndPrescription1;
    private javax.swing.JLabel patientReportLabel;
    private javax.swing.JLabel regLabel;
    private com.algounix.Laboretory.RegisterTests registerTests1;
    private com.algounix.Laboretory.TestList testList1;
    private javax.swing.JLabel testListLabel;
    // End of variables declaration//GEN-END:variables
}
