/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.algounix.Dashboards;

import com.algounix.Components.ScrollBar;
import com.algounix.GUI.SignOut;
import com.algounix.Panel.Reception.Invoice;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.JFrame;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author kusal
 */
public class DashboardReception extends javax.swing.JFrame {

    Timer updateTimer;
    int DELAY = 100;

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardReception() {
        initComponents();

        updateTimer = new Timer(DELAY, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Date currentTime = new Date();
                String TimeFormat = "HH:mm:ss";
                String DateFormat = "MMMM dd, yyyy";
                DateFormat formatTime = new SimpleDateFormat(TimeFormat);
                DateFormat formatDate = new SimpleDateFormat(DateFormat);
                String formattedTime = formatTime.format(currentTime);
                String formattedDate = formatDate.format(currentTime);
                jLabel3.setText(formattedTime);
                jLabel9.setText(formattedDate);

            }
        });

        updateTimer.start();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        FlatSVGIcon iconLogo = new FlatSVGIcon("com//algounix//Resources//HMS-Logo.svg", MenuLogo.getWidth(), MenuLogo.getHeight());
        MenuLogo.setIcon(iconLogo);
//        this.setIconImage(new ImageIcon("com//algounix//MenuIcons//GRN.png").getImage());
        Image icon = new ImageIcon(this.getClass().getResource("/com/algounix/Resources/HMS-Logo.png")).getImage();
        this.setIconImage(icon);
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AdminDashboardbtn = new javax.swing.JLabel();
        EmployeeListbtn = new javax.swing.JLabel();
        PatientListbtn = new javax.swing.JLabel();
        DoctorListbtn = new javax.swing.JLabel();
        PatientReportbtn = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        RoomPapbtn = new javax.swing.JLabel();
        StockListbtn = new javax.swing.JLabel();
        SupplierListbtn = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Appointmentbtn = new javax.swing.JLabel();
        AppointmentListbtn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AdminDashboardbtn2 = new javax.swing.JLabel();
        AdminDashboardbtn3 = new javax.swing.JLabel();
        StockListbtn1 = new javax.swing.JLabel();
        PatientRegbtn1 = new javax.swing.JLabel();
        AppointmentListbtn1 = new javax.swing.JLabel();
        PatientAdmitbtn2 = new javax.swing.JLabel();
        PatientAdmitbtn3 = new javax.swing.JLabel();
        Appointmentbtn1 = new javax.swing.JLabel();
        MenuLogo = new javax.swing.JLabel();
        AdminDashboardSignOutbtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CardLayoutPanel = new javax.swing.JPanel();
        dashboardReception1 = new com.algounix.Panel.Reception.DashboardReception();
        employeeReg1 = new com.algounix.Panel.EmployeeReg();
        receptionInvoiceReprint1 = new com.algounix.Panel.Reception.ReceptionInvoiceReprint();
        receptionPaymentHistory1 = new com.algounix.Panel.Reception.ReceptionPaymentHistory();
        roomMap1 = new com.algounix.Panel.RoomMap();
        doctorList1 = new com.algounix.Panel.DoctorList();
        employeeList1 = new com.algounix.Panel.EmployeeList();
        stockList1 = new com.algounix.Panel.BackOffice.StockList();
        supplierList1 = new com.algounix.Panel.SupplierList();
        pharmacyStockList1 = new com.algounix.Panel.Pharmacy.PharmacyStockList();
        patientAdmit1 = new com.algounix.Panel.Doctor.PatientAdmit();
        appointmentList1 = new com.algounix.Panel.Doctor.AppointmentList();
        reports1 = new com.algounix.Panel.Reports();
        patientDischarge1 = new com.algounix.Panel.Doctor.PatientDischarge();
        patientRegNew1 = new com.algounix.Panel.PatientRegNew();
        doctorChanellingList1 = new com.algounix.Panel.Doctor.DoctorChanellingList();
        addPatientQueList1 = new com.algounix.Panel.Reception.AddPatientQueList();
        patientAdmitList1 = new com.algounix.Panel.Doctor.PatientAdmitList();
        patientDischargeList1 = new com.algounix.Panel.Doctor.PatientDischargeList();
        patientReportAndPrescription1 = new com.algounix.Panel.Doctor.PatientReportAndPrescription();
        addAppoinment1 = new com.algounix.Panel.Reception.AddAppoinment();
        patientList1 = new com.algounix.Panel.Doctor.PatientList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(137, 207, 243));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 688));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(137, 207, 243));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Dashboard.png"))); // NOI18N
        jLabel1.setText("Dashboard");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Employee.png"))); // NOI18N
        jLabel2.setText("Invoice");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Patient.png"))); // NOI18N
        jLabel4.setText("Patient");

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Doctor.png"))); // NOI18N
        jLabel6.setText("Doctor");

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Rooms.png"))); // NOI18N
        jLabel8.setText("Rooms Management");

        jLabel12.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Appointment.png"))); // NOI18N
        jLabel12.setText("Appointment");

        AdminDashboardbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AdminDashboardbtn.setText("Reception Dashboard");
        AdminDashboardbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDashboardbtnMouseClicked(evt);
            }
        });

        EmployeeListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        EmployeeListbtn.setText("Employee List");
        EmployeeListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeListbtnMouseClicked(evt);
            }
        });

        PatientListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PatientListbtn.setText("Patient List");
        PatientListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientListbtnMouseClicked(evt);
            }
        });

        DoctorListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        DoctorListbtn.setText("Doctor List");
        DoctorListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorListbtnMouseClicked(evt);
            }
        });

        PatientReportbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PatientReportbtn.setText("Patient Reports & Prescription");
        PatientReportbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientReportbtnMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/GRN.png"))); // NOI18N
        jLabel25.setText("Stock Management");

        jLabel26.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Rooms.png"))); // NOI18N
        jLabel26.setText("Supplier Management");

        RoomPapbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        RoomPapbtn.setText("Room Map");
        RoomPapbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomPapbtnMouseClicked(evt);
            }
        });

        StockListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        StockListbtn.setText("Main Stock List");
        StockListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockListbtnMouseClicked(evt);
            }
        });

        SupplierListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        SupplierListbtn.setText("Supplier List");
        SupplierListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierListbtnMouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel39.setText("Reports");
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Report.png"))); // NOI18N
        jLabel38.setText("Reports");

        Appointmentbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        Appointmentbtn.setText("Add Appointment");
        Appointmentbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentbtnMouseClicked(evt);
            }
        });

        AppointmentListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AppointmentListbtn.setText("Chaneling List");
        AppointmentListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentListbtnMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Employee.png"))); // NOI18N
        jLabel7.setText("Employee");

        AdminDashboardbtn2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AdminDashboardbtn2.setText("Invoice Re-Print");
        AdminDashboardbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDashboardbtn2MouseClicked(evt);
            }
        });

        AdminDashboardbtn3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AdminDashboardbtn3.setText("Payment History");
        AdminDashboardbtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDashboardbtn3MouseClicked(evt);
            }
        });

        StockListbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        StockListbtn1.setText("Pharmacy Stock List");
        StockListbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockListbtn1MouseClicked(evt);
            }
        });

        PatientRegbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PatientRegbtn1.setText("Patient Registration New");
        PatientRegbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientRegbtn1MouseClicked(evt);
            }
        });

        AppointmentListbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AppointmentListbtn1.setText("OPD Que");
        AppointmentListbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentListbtn1MouseClicked(evt);
            }
        });

        PatientAdmitbtn2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PatientAdmitbtn2.setText("Admited Patient List");
        PatientAdmitbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientAdmitbtn2MouseClicked(evt);
            }
        });

        PatientAdmitbtn3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PatientAdmitbtn3.setText("Discharged Patient List");
        PatientAdmitbtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientAdmitbtn3MouseClicked(evt);
            }
        });

        Appointmentbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        Appointmentbtn1.setText("Appointment List");
        Appointmentbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Appointmentbtn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(AdminDashboardbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StockListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminDashboardbtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminDashboardbtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StockListbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomPapbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PatientReportbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(PatientAdmitbtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PatientAdmitbtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PatientListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PatientRegbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AppointmentListbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AppointmentListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Appointmentbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Appointmentbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminDashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminDashboardbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminDashboardbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientRegbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientAdmitbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientAdmitbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientReportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoctorListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoomPapbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockListbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupplierListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Appointmentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Appointmentbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppointmentListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppointmentListbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jScrollPane1.setViewportView(jPanel3);

        AdminDashboardSignOutbtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        AdminDashboardSignOutbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminDashboardSignOutbtn.setText("Sign Out");
        AdminDashboardSignOutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDashboardSignOutbtnMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins Light", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Unix Hospital");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(MenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDashboardSignOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDashboardSignOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(160, 233, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(803, 40));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 3, 18)); // NOI18N
        jLabel3.setText("12 : 30 AM");

        jLabel9.setFont(new java.awt.Font("Poppins Light", 3, 18)); // NOI18N
        jLabel9.setText("Date");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(765, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        CardLayoutPanel.setBackground(new java.awt.Color(205, 245, 253));
        CardLayoutPanel.setLayout(new java.awt.CardLayout());
        CardLayoutPanel.add(dashboardReception1, "card3");
        CardLayoutPanel.add(employeeReg1, "card3");
        CardLayoutPanel.add(receptionInvoiceReprint1, "card4");
        CardLayoutPanel.add(receptionPaymentHistory1, "card5");
        CardLayoutPanel.add(roomMap1, "card7");
        CardLayoutPanel.add(doctorList1, "card8");
        CardLayoutPanel.add(employeeList1, "card11");
        CardLayoutPanel.add(stockList1, "card12");
        CardLayoutPanel.add(supplierList1, "card13");
        CardLayoutPanel.add(pharmacyStockList1, "card15");
        CardLayoutPanel.add(patientAdmit1, "card16");
        CardLayoutPanel.add(appointmentList1, "card17");
        CardLayoutPanel.add(reports1, "card18");
        CardLayoutPanel.add(patientDischarge1, "card19");
        CardLayoutPanel.add(patientRegNew1, "card20");
        CardLayoutPanel.add(doctorChanellingList1, "card21");
        CardLayoutPanel.add(addPatientQueList1, "card22");
        CardLayoutPanel.add(patientAdmitList1, "card23");
        CardLayoutPanel.add(patientDischargeList1, "card24");
        CardLayoutPanel.add(patientReportAndPrescription1, "card25");
        CardLayoutPanel.add(addAppoinment1, "card25");
        CardLayoutPanel.add(patientList1, "card23");

        jPanel4.add(CardLayoutPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminDashboardbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(dashboardReception1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AdminDashboardbtnMouseClicked

    private void AdminDashboardSignOutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardSignOutbtnMouseClicked
        // TODO add your handling code here:
//        GlassPanePopup.showPopup(new Navigation());
        new SignOut().setVisible(true);
    }//GEN-LAST:event_AdminDashboardSignOutbtnMouseClicked

    private void AdminDashboardbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardbtn2MouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(receptionInvoiceReprint1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AdminDashboardbtn2MouseClicked

    private void AdminDashboardbtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardbtn3MouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(receptionPaymentHistory1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AdminDashboardbtn3MouseClicked

    private void EmployeeListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeListbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(employeeList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_EmployeeListbtnMouseClicked

    private void PatientListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientListbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_PatientListbtnMouseClicked

    private void PatientReportbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientReportbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientReportAndPrescription1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_PatientReportbtnMouseClicked

    private void DoctorListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorListbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(doctorList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_DoctorListbtnMouseClicked

    private void RoomPapbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomPapbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(roomMap1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_RoomPapbtnMouseClicked

    private void StockListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockListbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(stockList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_StockListbtnMouseClicked

    private void SupplierListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierListbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(supplierList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_SupplierListbtnMouseClicked

    private void AppointmentbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(addAppoinment1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AppointmentbtnMouseClicked

    private void StockListbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockListbtn1MouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(pharmacyStockList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_StockListbtn1MouseClicked

    private void AppointmentListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentListbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(doctorChanellingList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AppointmentListbtnMouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(reports1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_jLabel39MouseClicked

    private void PatientRegbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientRegbtn1MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientRegNew1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_PatientRegbtn1MouseClicked

    private void AppointmentListbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentListbtn1MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(addPatientQueList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AppointmentListbtn1MouseClicked

    private void PatientAdmitbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientAdmitbtn2MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientAdmitList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_PatientAdmitbtn2MouseClicked

    private void PatientAdmitbtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientAdmitbtn3MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientDischargeList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_PatientAdmitbtn3MouseClicked

    private void Appointmentbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Appointmentbtn1MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(appointmentList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_Appointmentbtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardReception().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboardSignOutbtn;
    private javax.swing.JLabel AdminDashboardbtn;
    private javax.swing.JLabel AdminDashboardbtn2;
    private javax.swing.JLabel AdminDashboardbtn3;
    private javax.swing.JLabel AppointmentListbtn;
    private javax.swing.JLabel AppointmentListbtn1;
    private javax.swing.JLabel Appointmentbtn;
    private javax.swing.JLabel Appointmentbtn1;
    private javax.swing.JPanel CardLayoutPanel;
    private javax.swing.JLabel DoctorListbtn;
    private javax.swing.JLabel EmployeeListbtn;
    private javax.swing.JLabel MenuLogo;
    private javax.swing.JLabel PatientAdmitbtn2;
    private javax.swing.JLabel PatientAdmitbtn3;
    private javax.swing.JLabel PatientListbtn;
    private javax.swing.JLabel PatientRegbtn1;
    private javax.swing.JLabel PatientReportbtn;
    private javax.swing.JLabel RoomPapbtn;
    private javax.swing.JLabel StockListbtn;
    private javax.swing.JLabel StockListbtn1;
    private javax.swing.JLabel SupplierListbtn;
    private com.algounix.Panel.Reception.AddAppoinment addAppoinment1;
    private com.algounix.Panel.Reception.AddPatientQueList addPatientQueList1;
    private com.algounix.Panel.Doctor.AppointmentList appointmentList1;
    private com.algounix.Panel.Reception.DashboardReception dashboardReception1;
    private com.algounix.Panel.Doctor.DoctorChanellingList doctorChanellingList1;
    private com.algounix.Panel.DoctorList doctorList1;
    private com.algounix.Panel.EmployeeList employeeList1;
    private com.algounix.Panel.EmployeeReg employeeReg1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.algounix.Panel.Doctor.PatientAdmit patientAdmit1;
    private com.algounix.Panel.Doctor.PatientAdmitList patientAdmitList1;
    private com.algounix.Panel.Doctor.PatientDischarge patientDischarge1;
    private com.algounix.Panel.Doctor.PatientDischargeList patientDischargeList1;
    private com.algounix.Panel.Doctor.PatientList patientList1;
    private com.algounix.Panel.PatientRegNew patientRegNew1;
    private com.algounix.Panel.Doctor.PatientReportAndPrescription patientReportAndPrescription1;
    private com.algounix.Panel.Pharmacy.PharmacyStockList pharmacyStockList1;
    private com.algounix.Panel.Reception.ReceptionInvoiceReprint receptionInvoiceReprint1;
    private com.algounix.Panel.Reception.ReceptionPaymentHistory receptionPaymentHistory1;
    private com.algounix.Panel.Reports reports1;
    private com.algounix.Panel.RoomMap roomMap1;
    private com.algounix.Panel.BackOffice.StockList stockList1;
    private com.algounix.Panel.SupplierList supplierList1;
    // End of variables declaration//GEN-END:variables
}
