/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.algounix.Dashboards;

import com.algounix.Components.ScrollBar;
import com.algounix.GUI.SignOut;
import com.algounix.Panel.BackOffice.Brand;
import com.algounix.Panel.BackOffice.GRNList;
import com.algounix.Panel.BackOffice.Product;
import com.algounix.Panel.CompanyReg;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Frame;
import javax.swing.JFrame;
import java.awt.Image;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author kusal
 */
public class DashboardAdmin extends javax.swing.JFrame {

    Timer updateTimer;
    int DELAY = 100;

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();

        updateTimer = new Timer(DELAY, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Date currentTime = new Date();
                String TimeFormat = "HH:mm:ss";
                String DateFormat = "MMMM dd, yyyy";
                DateFormat formatTime = new SimpleDateFormat(TimeFormat);
                DateFormat formatDate = new SimpleDateFormat(DateFormat);
                String formattedTime = formatTime.format(currentTime);
                String formattedDate = formatDate.format(currentTime);
                jLabel3.setText(formattedTime);
                jLabel9.setText(formattedDate);

            }
        });

        updateTimer.start();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        FlatSVGIcon iconLogo = new FlatSVGIcon("com//algounix//Resources//HMS-Logo.svg", MenuLogo.getWidth(), MenuLogo.getHeight());
        MenuLogo.setIcon(iconLogo);
        this.setIconImage(new ImageIcon("com//algounix//MenuIcons//GRN.png").getImage());
        Image icon = new ImageIcon(this.getClass().getResource("/com/algounix/Resources/HMS-Logo.png")).getImage();
        this.setIconImage(icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AdminDashboardbtn = new javax.swing.JLabel();
        EmployeeRegbtn = new javax.swing.JLabel();
        EmployeeListbtn = new javax.swing.JLabel();
        PatientListbtn = new javax.swing.JLabel();
        DoctorRegbtn = new javax.swing.JLabel();
        DoctorListbtn = new javax.swing.JLabel();
        DoctorReportbtn = new javax.swing.JLabel();
        PatientReportbtn = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        RoomPapbtn = new javax.swing.JLabel();
        RoomsReservationbtn = new javax.swing.JLabel();
        GRNbtn = new javax.swing.JLabel();
        Stockbtn = new javax.swing.JLabel();
        AddProductbtn = new javax.swing.JLabel();
        StockTransferbtn = new javax.swing.JLabel();
        StockListbtn = new javax.swing.JLabel();
        SupplierRegbtn = new javax.swing.JLabel();
        SupplierListbtn = new javax.swing.JLabel();
        CompanyRegbtn = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Appointmentbtn = new javax.swing.JLabel();
        AppointmentListbtn = new javax.swing.JLabel();
        BrandRegbtn = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        AppointmentListbtn1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        AppointmentListbtn2 = new javax.swing.JLabel();
        StockListbtn1 = new javax.swing.JLabel();
        StockTransferbtn1 = new javax.swing.JLabel();
        GRNbtn1 = new javax.swing.JLabel();
        DoctorListbtn1 = new javax.swing.JLabel();
        PatientAdmitbtn2 = new javax.swing.JLabel();
        PatientAdmitbtn3 = new javax.swing.JLabel();
        AppointmentListbtn3 = new javax.swing.JLabel();
        DoctorReportbtn1 = new javax.swing.JLabel();
        MenuLogo = new javax.swing.JLabel();
        AdminDashboardSignOutbtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        minimizebtn = new com.algounix.Buttons.WindowButton();
        closebtn = new com.algounix.Buttons.WindowButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CardLayoutPanel = new javax.swing.JPanel();
        dashboard1 = new com.algounix.Panel.Dashboard();
        employeeReg1 = new com.algounix.Panel.EmployeeReg();
        employeeList1 = new com.algounix.Panel.EmployeeList();
        GRN1 = new com.algounix.Panel.GRN();
        roomMap1 = new com.algounix.Panel.RoomMap();
        doctorList1 = new com.algounix.Panel.DoctorList();
        supplierReg1 = new com.algounix.Panel.BackOffice.SupplierReg();
        stock1 = new com.algounix.Panel.BackOffice.Stock();
        supplierList1 = new com.algounix.Panel.SupplierList();
        reports2 = new com.algounix.Panel.Reports();
        updateRoom1 = new com.algounix.Panel.UpdateRoom();
        appointmentList1 = new com.algounix.Panel.Doctor.AppointmentList();
        changePasswords1 = new com.algounix.Panel.ChangePasswords();
        doctorAttendunce1 = new com.algounix.Panel.Doctor.DoctorAttendunce();
        stockList1 = new com.algounix.Panel.BackOffice.StockList();
        pharmacyStockList1 = new com.algounix.Panel.Pharmacy.PharmacyStockList();
        addAppoinment1 = new com.algounix.Panel.Reception.AddAppoinment();
        doctorReg1 = new com.algounix.Panel.Doctor.DoctorReg();
        hospitalStockTransfer1 = new com.algounix.Panel.BackOffice.HospitalStockTransfer();
        doctorCharges1 = new com.algounix.Panel.DoctorCharges();
        pharmacyStockTransfer1 = new com.algounix.Panel.Pharmacy.PharmacyStockTransfer();
        patientReportAndPrescription1 = new com.algounix.Panel.Doctor.PatientReportAndPrescription();
        patientDischargeList1 = new com.algounix.Panel.Doctor.PatientDischargeList();
        doctorChanellingList1 = new com.algounix.Panel.Doctor.DoctorChanellingList();
        patientAdmitList1 = new com.algounix.Panel.Doctor.PatientAdmitList();
        patientList1 = new com.algounix.Panel.Doctor.PatientList();
        employeeSalary1 = new com.algounix.Panel.EmployeeSalary();
        employeeSalaryList1 = new com.algounix.Panel.EmployeeSalaryList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(137, 207, 243));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 688));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(137, 207, 243));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Dashboard.png"))); // NOI18N
        jLabel1.setText("Dashboard");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Employee.png"))); // NOI18N
        jLabel2.setText("Employee");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Patient.png"))); // NOI18N
        jLabel4.setText("Patient");

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Doctor.png"))); // NOI18N
        jLabel6.setText("Doctor");

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Rooms.png"))); // NOI18N
        jLabel8.setText("Rooms Management");

        jLabel12.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Appointment.png"))); // NOI18N
        jLabel12.setText("Appointment");

        AdminDashboardbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AdminDashboardbtn.setText("Admin Dashboard");
        AdminDashboardbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDashboardbtnMouseClicked(evt);
            }
        });

        EmployeeRegbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        EmployeeRegbtn.setText("Employee Registration");
        EmployeeRegbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeRegbtnMouseClicked(evt);
            }
        });

        EmployeeListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        EmployeeListbtn.setText("Employee List");
        EmployeeListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeListbtnMouseClicked(evt);
            }
        });

        PatientListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PatientListbtn.setText("Patient List");
        PatientListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientListbtnMouseClicked(evt);
            }
        });

        DoctorRegbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        DoctorRegbtn.setText("Doctor Registration");
        DoctorRegbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorRegbtnMouseClicked(evt);
            }
        });

        DoctorListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        DoctorListbtn.setText("Doctor List");
        DoctorListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorListbtnMouseClicked(evt);
            }
        });

        DoctorReportbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        DoctorReportbtn.setText("Doctor Attendence");
        DoctorReportbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorReportbtnMouseClicked(evt);
            }
        });

        PatientReportbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PatientReportbtn.setText("Patient Report & Prescription");
        PatientReportbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientReportbtnMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/GRN.png"))); // NOI18N
        jLabel25.setText("Stock Management");

        jLabel26.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Rooms.png"))); // NOI18N
        jLabel26.setText("Supplier Management");

        RoomPapbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        RoomPapbtn.setText("Room Map");
        RoomPapbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomPapbtnMouseClicked(evt);
            }
        });

        RoomsReservationbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        RoomsReservationbtn.setText("Update Room");
        RoomsReservationbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomsReservationbtnMouseClicked(evt);
            }
        });

        GRNbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        GRNbtn.setText("GRN");
        GRNbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRNbtnMouseClicked(evt);
            }
        });

        Stockbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        Stockbtn.setText("Stock");
        Stockbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockbtnMouseClicked(evt);
            }
        });

        AddProductbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AddProductbtn.setText("Add Product");
        AddProductbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductbtnMouseClicked(evt);
            }
        });

        StockTransferbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        StockTransferbtn.setText("Hostpital Stock Transfer");
        StockTransferbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockTransferbtnMouseClicked(evt);
            }
        });

        StockListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        StockListbtn.setText("Main Stock List");
        StockListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockListbtnMouseClicked(evt);
            }
        });

        SupplierRegbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        SupplierRegbtn.setText("Supplier Registration");
        SupplierRegbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierRegbtnMouseClicked(evt);
            }
        });

        SupplierListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        SupplierListbtn.setText("Supplier List");
        SupplierListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierListbtnMouseClicked(evt);
            }
        });

        CompanyRegbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        CompanyRegbtn.setText("Company Registration");
        CompanyRegbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompanyRegbtnMouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel39.setText("Change Passwords");
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Report.png"))); // NOI18N
        jLabel38.setText("Reports");

        Appointmentbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        Appointmentbtn.setText("Add Appointment");
        Appointmentbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentbtnMouseClicked(evt);
            }
        });

        AppointmentListbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AppointmentListbtn.setText("Appointment List");
        AppointmentListbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentListbtnMouseClicked(evt);
            }
        });

        BrandRegbtn.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        BrandRegbtn.setText("Brand Registration");
        BrandRegbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrandRegbtnMouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Employee.png"))); // NOI18N
        jLabel41.setText("Settings");

        AppointmentListbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AppointmentListbtn1.setText("Reports");
        AppointmentListbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentListbtn1MouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/algounix/MenuIcons/Report.png"))); // NOI18N
        jLabel43.setText("Salary");

        AppointmentListbtn2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AppointmentListbtn2.setText("Calculate Employee Salary");
        AppointmentListbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentListbtn2MouseClicked(evt);
            }
        });

        StockListbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        StockListbtn1.setText("Pharmacy Stock List");
        StockListbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockListbtn1MouseClicked(evt);
            }
        });

        StockTransferbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        StockTransferbtn1.setText("Pharmacy Stock Transfer");
        StockTransferbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockTransferbtn1MouseClicked(evt);
            }
        });

        GRNbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        GRNbtn1.setText("GRN List");
        GRNbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GRNbtn1MouseClicked(evt);
            }
        });

        DoctorListbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        DoctorListbtn1.setText("Doctor Channeling List");
        DoctorListbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorListbtn1MouseClicked(evt);
            }
        });

        PatientAdmitbtn2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PatientAdmitbtn2.setText("Patient Discharge List");
        PatientAdmitbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientAdmitbtn2MouseClicked(evt);
            }
        });

        PatientAdmitbtn3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        PatientAdmitbtn3.setText("Patient Admit List");
        PatientAdmitbtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientAdmitbtn3MouseClicked(evt);
            }
        });

        AppointmentListbtn3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        AppointmentListbtn3.setText("Employee Salary List");
        AppointmentListbtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentListbtn3MouseClicked(evt);
            }
        });

        DoctorReportbtn1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        DoctorReportbtn1.setText("Doctor Fees");
        DoctorReportbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorReportbtn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(AdminDashboardbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AppointmentListbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorRegbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AppointmentListbtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AppointmentListbtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EmployeeListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmployeeRegbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PatientReportbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(PatientAdmitbtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PatientAdmitbtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PatientListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RoomsReservationbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(RoomPapbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(StockListbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StockListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddProductbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StockTransferbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Stockbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GRNbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GRNbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StockTransferbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BrandRegbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CompanyRegbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(SupplierListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SupplierRegbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AppointmentListbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Appointmentbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(DoctorListbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DoctorReportbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addComponent(DoctorListbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DoctorReportbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminDashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeRegbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientAdmitbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientAdmitbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientReportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoctorRegbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorListbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorReportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorReportbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RoomPapbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoomsReservationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GRNbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GRNbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stockbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockTransferbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockTransferbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddProductbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockListbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SupplierRegbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupplierListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompanyRegbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BrandRegbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Appointmentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppointmentListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AppointmentListbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AppointmentListbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppointmentListbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jScrollPane1.setViewportView(jPanel3);

        AdminDashboardSignOutbtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        AdminDashboardSignOutbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminDashboardSignOutbtn.setText("Sign Out");
        AdminDashboardSignOutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDashboardSignOutbtnMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins Light", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Unix Hospital");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(MenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDashboardSignOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDashboardSignOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(160, 233, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(803, 40));

        minimizebtn.setBackground(new java.awt.Color(255, 204, 51));
        minimizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizebtnActionPerformed(evt);
            }
        });

        closebtn.setBackground(new java.awt.Color(255, 51, 51));
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins Light", 3, 18)); // NOI18N
        jLabel3.setText("12 : 30 AM");

        jLabel9.setFont(new java.awt.Font("Poppins Light", 3, 18)); // NOI18N
        jLabel9.setText("Date");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 686, Short.MAX_VALUE)
                .addComponent(minimizebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(closebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        CardLayoutPanel.setBackground(new java.awt.Color(205, 245, 253));
        CardLayoutPanel.setLayout(new java.awt.CardLayout());
        CardLayoutPanel.add(dashboard1, "card32");
        CardLayoutPanel.add(employeeReg1, "card3");
        CardLayoutPanel.add(employeeList1, "card4");
        CardLayoutPanel.add(GRN1, "card9");
        CardLayoutPanel.add(roomMap1, "card10");
        CardLayoutPanel.add(doctorList1, "card11");
        CardLayoutPanel.add(supplierReg1, "card13");
        CardLayoutPanel.add(stock1, "card14");
        CardLayoutPanel.add(supplierList1, "card15");
        CardLayoutPanel.add(reports2, "card17");
        CardLayoutPanel.add(updateRoom1, "card20");
        CardLayoutPanel.add(appointmentList1, "card22");
        CardLayoutPanel.add(changePasswords1, "card23");
        CardLayoutPanel.add(doctorAttendunce1, "card28");
        CardLayoutPanel.add(stockList1, "card29");
        CardLayoutPanel.add(pharmacyStockList1, "card30");
        CardLayoutPanel.add(addAppoinment1, "card29");
        CardLayoutPanel.add(doctorReg1, "card29");
        CardLayoutPanel.add(hospitalStockTransfer1, "card30");
        CardLayoutPanel.add(doctorCharges1, "card29");
        CardLayoutPanel.add(pharmacyStockTransfer1, "card30");
        CardLayoutPanel.add(patientReportAndPrescription1, "card29");
        CardLayoutPanel.add(patientDischargeList1, "card31");
        CardLayoutPanel.add(doctorChanellingList1, "card32");
        CardLayoutPanel.add(patientAdmitList1, "card33");
        CardLayoutPanel.add(patientList1, "card33");
        CardLayoutPanel.add(employeeSalary1, "card34");
        CardLayoutPanel.add(employeeSalaryList1, "card32");

        jPanel4.add(CardLayoutPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closebtnActionPerformed

    private void minimizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizebtnActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizebtnActionPerformed

    private void AdminDashboardbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(dashboard1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AdminDashboardbtnMouseClicked

    private void EmployeeRegbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeRegbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(employeeReg1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_EmployeeRegbtnMouseClicked

    private void AdminDashboardSignOutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardSignOutbtnMouseClicked
        // TODO add your handling code here:
        new SignOut().setVisible(true);
    }//GEN-LAST:event_AdminDashboardSignOutbtnMouseClicked

    private void EmployeeListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeListbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(employeeList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_EmployeeListbtnMouseClicked

    private void PatientListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientListbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_PatientListbtnMouseClicked

    private void PatientReportbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientReportbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientReportAndPrescription1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_PatientReportbtnMouseClicked

    private void GRNbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(GRN1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_GRNbtnMouseClicked

    private void RoomPapbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomPapbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(roomMap1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_RoomPapbtnMouseClicked

    private void AppointmentbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(addAppoinment1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AppointmentbtnMouseClicked

    private void SupplierRegbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierRegbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(supplierReg1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_SupplierRegbtnMouseClicked

    private void StockbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(stock1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_StockbtnMouseClicked

    private void CompanyRegbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompanyRegbtnMouseClicked
        // TODO add your handling code here:
        Window window = SwingUtilities.getWindowAncestor(this);

        CompanyReg dialog = new CompanyReg((Frame) window);
        dialog.setVisible(true);
    }//GEN-LAST:event_CompanyRegbtnMouseClicked

    private void SupplierListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierListbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(supplierList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_SupplierListbtnMouseClicked

    private void AddProductbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductbtnMouseClicked
        // TODO add your handling code here:
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        Product AP = new Product(parentFrame, true);
        AP.setVisible(true);
    }//GEN-LAST:event_AddProductbtnMouseClicked

    private void BrandRegbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrandRegbtnMouseClicked
        // TODO add your handling code here:
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        Brand BR = new Brand(parentFrame, true);
        BR.setVisible(true);
    }//GEN-LAST:event_BrandRegbtnMouseClicked

    private void AppointmentListbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentListbtn1MouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(reports2);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AppointmentListbtn1MouseClicked

    private void StockListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockListbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(stockList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

    }//GEN-LAST:event_StockListbtnMouseClicked

    private void RoomsReservationbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomsReservationbtnMouseClicked
        // TODO add your handling code here:
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(updateRoom1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

    }//GEN-LAST:event_RoomsReservationbtnMouseClicked

    private void StockTransferbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockTransferbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(hospitalStockTransfer1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_StockTransferbtnMouseClicked

    private void AppointmentListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentListbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(appointmentList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AppointmentListbtnMouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(changePasswords1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_jLabel39MouseClicked

    private void DoctorRegbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorRegbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(doctorReg1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_DoctorRegbtnMouseClicked

    private void DoctorListbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorListbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(doctorList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_DoctorListbtnMouseClicked

    private void DoctorReportbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorReportbtnMouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(doctorAttendunce1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_DoctorReportbtnMouseClicked

    private void AppointmentListbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentListbtn2MouseClicked
        // TODO add your handling code here:
        //Remove Panel

        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(employeeSalary1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

    }//GEN-LAST:event_AppointmentListbtn2MouseClicked

    private void StockListbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockListbtn1MouseClicked
        // TODO add your handling code here:
        //Remove Panel

        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(pharmacyStockList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_StockListbtn1MouseClicked

    private void StockTransferbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockTransferbtn1MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(pharmacyStockTransfer1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_StockTransferbtn1MouseClicked

    private void GRNbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GRNbtn1MouseClicked
        // TODO add your handling code here:
        GRNList GRNL = new GRNList();
        GRNL.setVisible(true);
    }//GEN-LAST:event_GRNbtn1MouseClicked

    private void DoctorListbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorListbtn1MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(doctorChanellingList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_DoctorListbtn1MouseClicked

    private void PatientAdmitbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientAdmitbtn2MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientDischargeList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_PatientAdmitbtn2MouseClicked

    private void PatientAdmitbtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientAdmitbtn3MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(patientAdmitList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_PatientAdmitbtn3MouseClicked

    private void AppointmentListbtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentListbtn3MouseClicked
        // TODO add your handling code here:
        //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(employeeSalaryList1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_AppointmentListbtn3MouseClicked

    private void DoctorReportbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorReportbtn1MouseClicked
        // TODO add your handling code here:
          //Remove Panel
        CardLayoutPanel.removeAll();
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();

        //Add Panel
        CardLayoutPanel.add(doctorCharges1);
        CardLayoutPanel.repaint();
        CardLayoutPanel.revalidate();
    }//GEN-LAST:event_DoctorReportbtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddProductbtn;
    private javax.swing.JLabel AdminDashboardSignOutbtn;
    private javax.swing.JLabel AdminDashboardbtn;
    private javax.swing.JLabel AppointmentListbtn;
    private javax.swing.JLabel AppointmentListbtn1;
    private javax.swing.JLabel AppointmentListbtn2;
    private javax.swing.JLabel AppointmentListbtn3;
    private javax.swing.JLabel Appointmentbtn;
    private javax.swing.JLabel BrandRegbtn;
    private javax.swing.JPanel CardLayoutPanel;
    private javax.swing.JLabel CompanyRegbtn;
    private javax.swing.JLabel DoctorListbtn;
    private javax.swing.JLabel DoctorListbtn1;
    private javax.swing.JLabel DoctorRegbtn;
    private javax.swing.JLabel DoctorReportbtn;
    private javax.swing.JLabel DoctorReportbtn1;
    private javax.swing.JLabel EmployeeListbtn;
    private javax.swing.JLabel EmployeeRegbtn;
    private com.algounix.Panel.GRN GRN1;
    private javax.swing.JLabel GRNbtn;
    private javax.swing.JLabel GRNbtn1;
    private javax.swing.JLabel MenuLogo;
    private javax.swing.JLabel PatientAdmitbtn2;
    private javax.swing.JLabel PatientAdmitbtn3;
    private javax.swing.JLabel PatientListbtn;
    private javax.swing.JLabel PatientReportbtn;
    private javax.swing.JLabel RoomPapbtn;
    private javax.swing.JLabel RoomsReservationbtn;
    private javax.swing.JLabel StockListbtn;
    private javax.swing.JLabel StockListbtn1;
    private javax.swing.JLabel StockTransferbtn;
    private javax.swing.JLabel StockTransferbtn1;
    private javax.swing.JLabel Stockbtn;
    private javax.swing.JLabel SupplierListbtn;
    private javax.swing.JLabel SupplierRegbtn;
    private com.algounix.Panel.Reception.AddAppoinment addAppoinment1;
    private com.algounix.Panel.Doctor.AppointmentList appointmentList1;
    private com.algounix.Panel.ChangePasswords changePasswords1;
    private com.algounix.Buttons.WindowButton closebtn;
    private com.algounix.Panel.Dashboard dashboard1;
    private com.algounix.Panel.Doctor.DoctorAttendunce doctorAttendunce1;
    private com.algounix.Panel.Doctor.DoctorChanellingList doctorChanellingList1;
    private com.algounix.Panel.DoctorCharges doctorCharges1;
    private com.algounix.Panel.DoctorList doctorList1;
    private com.algounix.Panel.Doctor.DoctorReg doctorReg1;
    private com.algounix.Panel.EmployeeList employeeList1;
    private com.algounix.Panel.EmployeeReg employeeReg1;
    private com.algounix.Panel.EmployeeSalary employeeSalary1;
    private com.algounix.Panel.EmployeeSalaryList employeeSalaryList1;
    private com.algounix.Panel.BackOffice.HospitalStockTransfer hospitalStockTransfer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.algounix.Buttons.WindowButton minimizebtn;
    private com.algounix.Panel.Doctor.PatientAdmitList patientAdmitList1;
    private com.algounix.Panel.Doctor.PatientDischargeList patientDischargeList1;
    private com.algounix.Panel.Doctor.PatientList patientList1;
    private com.algounix.Panel.Doctor.PatientReportAndPrescription patientReportAndPrescription1;
    private com.algounix.Panel.Pharmacy.PharmacyStockList pharmacyStockList1;
    private com.algounix.Panel.Pharmacy.PharmacyStockTransfer pharmacyStockTransfer1;
    private com.algounix.Panel.Reports reports2;
    private com.algounix.Panel.RoomMap roomMap1;
    private com.algounix.Panel.BackOffice.Stock stock1;
    private com.algounix.Panel.BackOffice.StockList stockList1;
    private com.algounix.Panel.SupplierList supplierList1;
    private com.algounix.Panel.BackOffice.SupplierReg supplierReg1;
    private com.algounix.Panel.UpdateRoom updateRoom1;
    // End of variables declaration//GEN-END:variables
}
